AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: "773910315572.dkr.ecr.us-east-1.amazonaws.com/cicd-nodeserver-ecs:latest"
          Name: "cicd-nodeserver-ecs"
          PortMappings:
            - ContainerPort: 3001
              HostPort: 3001
              Protocol: "tcp"
            - ContainerPort: 80
              HostPort: 80
              Protocol: "tcp"
      Family: "cicd-nodeserver-ecs"
      TaskRoleArn: "arn:aws:iam::773910315572:role/ecsTaskExecutionRole"
      ExecutionRoleArn: "arn:aws:iam::773910315572:role/ecsTaskExecutionRole"
      RequiresCompatibilities:
        - "EC2"
      Cpu: "128"
      Memory: "300"
