# ECS Service
Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: "cicd-nodeserver-ecs-service"
      Cluster: "cicd-nodeserver-ecs-cluster"
      LaunchType: EC2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: 1
      TaskDefinition: "arn:aws:ecs:us-east-1:773910315572:task-definition/cicd-nodeserver-ecs:3"
